### ISSUE TITLE
SRFIs tracking issue (100–199)

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/vim-r7rs-syntax#11]
For SRFIs 0–99, see #7.
For SRFIs 200–, see #44.

## List of SRFIs (100–199)

- [ ] SRFI 100: Define-lambda-object
- [-] SRFI 101: Purely functional random-access pairs and lists (part of R7RS large)
- [-] SRFI 105: Curly-infix-expressions (won't support)
- [ ] #25
- [ ] SRFI 107: XML reader syntax
- [ ] SRFI 108: Named quasi-literal constructors
- [ ] SRFI 109: Extended string quasi-literals
- [-] SRFI 110: Sweet-expressions (t-espressions) (won't support)
- [-] SRFI 111: Boxes (part of R7RS large)
- [x] SRFI 112: Environment inquiry (#12)
- [-] SRFI 113: Sets and bags (part of R7RS large)
- [-] SRFI 115: Scheme regular expressions (part of R7RS large)
- [-] SRFI 116: Immutable list library (part of R7RS large)
- [-] SRFI 117: Queues based on lists (part of R7RS large)
- [x] SRFI 118: Simple adjustable-size strings (#13)
- [-] SRFI 119: wisp: simpler indentation-sensitive scheme (won't support)
- [x] SRFI 120: Timer APIs (#14)
- [ ] SRFI 122: Nonempty intervals and generalized arrays
- [ ] SRFI 123: Generic accessor and modifier
- [-] SRFI 124: Ephemerons (part of R7RS large)
- [-] SRFI 125: Intermediate hash tables (part of R7RS large)
- [ ] SRFI 126: R6RS-based hashtables
- [-] SRFI 127: Lazy sequences (part of R7RS large)
- [-] SRFI 128: Comparators (reduced) (part of R7RS large)
- [x] SRFI 129: Titlecase procedures (#15)
- [ ] SRFI 130: Cursor-based string library (#16)
- [ ] SRFI 131: ERR5RS record syntax (reduced)
- [-] SRFI 132: Sort libraries (part of R7RS large)
- [-] SRFI 133: Vector library (R7RS-compatible) (part of R7RS large)
- [-] SRFI 134: Immutable dequeues (part of R7RS large)
- [-] SRFI 135: Immutable texts (part of R7RS large)
- [ ] SRFI 136: Extensible record types
- [ ] SRFI 137: Minimal unique types
- [ ] SRFI 138: Compiling Scheme programs to executables
- [ ] SRFI 139: Syntax parameters
- [ ] SRFI 140: Immutable strings
- [-] SRFI 141: Integer devision (part of R7RS large)
- [-] SRFI 143: Fixnums (part of R7RS large)
- [-] SRFI 144: Flonums (part of R7RS large)
- [x] #22
- [-] SRFI 146: Mappings (part of R7RS large)
- [ ] SRFI 147: Custom macro transformers
- [ ] SRFI 148: Eager syntax-rules
- [ ] SRFI 149: Basic syntax-rules template extensions
- [ ] SRFI 150: Hygienic ERR5RS record syntax (reduced)
- [ ] SRFI 151: Bitwise operations
- [x] #54
- [ ] SRFI 154: First-class dynamic extents
- [ ] SRFI 155: Promises
- [ ] SRFI 156: Syntactic combiners for binary predicates
- [ ] SRFI 157: Continuation marks
- [-] SRFI 158: Generators and accumulators (part of R7RS large)
- [-] SRFI 160: Homogeneous numeric vector libraries (part of R7RS large)
- [ ] SRFI 161: Unifiable boxes
- [ ] SRFI 162: Comparator sublibrary
- [ ] SRFI 163: Enhanced array literals
- [ ] SRFI 164: Enhanced multi-dimensional arrays
- [ ] SRFI 165: The environment monad
- [ ] SRFI 166: Monadic formatting
- [ ] SRFI 167: Ordered key value store
- [ ] SRFI 168: Generic tuple store database
- [ ] SRFI 169: Underscore in numbers
- [ ] SRFI 170: POSIX API
- [ ] SRFI 171: Transducers
- [-] SRFI 172: Two safer subsets of R7RS (no new keywords)
- [ ] SRFI 173: Hooks
- [ ] SRFI 174: POSIX timespecs
- [ ] SRFI 175: ASCII character library
- [ ] SRFI 176: Version flag
- [ ] SRFI 178: Bitvector library
- [ ] SRFI 179: Nonempty intervals and generalized arrays (updated)
- [ ] #84
- [ ] #83
- [ ] #56
- [ ] #82
- [ ] #81
- [ ] #79
- [ ] #80
- [ ] #78
- [ ] #77
- [-] SRFI 195: Multiple-value boxes (no new keywords; same as SRFI 111)
- [ ] #76
- [ ] #75

## References
* [SRFIs (status: final)](https://srfi.schemers.org/?sort=number-asc&statuses=final)
* [Gauche manual: SRFIs](http://practical-scheme.net/gauche/man/gauche-refe-draft/Standard-conformance.html#Standard-conformance)
