### ISSUE TITLE
SRFIs tracking issue (0–99)

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/vim-r7rs-syntax#7]
For SRFIs 100–199, see #11 .
For SRFIs 200–, see #44.

## List of SRFIs (0–99)

- [-] SRFI 0: Feature-based conditional expansion construct (part of R7RS small)
- [-] SRFI 1: List library (part of R7RS large)
- [x] SRFI 2: AND-LET\*: an AND with local bindings, a guarded LET\* special form (#9)
- [-] SRFI 4: Homogeneous numeric vector datatypes (part of R7RS large)
- [-] SRFI 5: A compatible let form with signatures and rest arguments (no new keywords)
- [-] SRFI 6: Basic string ports (part of R7RS small)
- [ ] #31
- [x] #28
- [-] SRFI 9: Defining record types (part of R7RS small)
- [ ] #30
- [-] SRFI 11: Syntax for receiving multiple values (part of R7RS small)
- [ ] #32
- [-] SRFI 14: Character-set library (part of R7RS large)
- [-] SRFI 16: Syntax for procedures of variable arity (part of R7RS small)
- [x] #33
- [x] #34
- [ ] #35
- [x] #52
- [x] #36
- [-] SRFI 23: Error reporting mechanism (part of R7RS small)
- [x] #50
- [x] #48
- [x] #46
- [ ] SRFI 28: Basic format strings
- [ ] SRFI 29: Localization
- [-] SRFI 30: Nested multi-Line comments (part of R7RS small)
- [ ] SRFI 31: A special form `rec` for recursive evaluation
- [-] SRFI 34: Exception handling for programs (part of R7RS small)
- [ ] SRFI 35: Conditions
- [ ] SRFI 36: I/O conditions
- [ ] SRFI 37: args-fold: a program argument processor
- [ ] SRFI 38: External representation for data with shared structure
- [-] SRFI 39: Parameter objects (part of R7RS small)
- [-] SRFI 41: Streams (part of R7RS large)
- [ ] SRFI 42: Eager comprehensions
- [ ] SRFI 43: Vector library (legacy)
- [ ] SRFI 44: Collections
- [ ] SRFI 45: Primitives for expressing iterative lazy algorithms
- [-] SRFI 46: Basic syntax-rules extensions (part of R7RS small)
- [ ] SRFI 47: Array
- [ ] SRFI 48: Intermediate format strings
- [-] SRFI 49: Indentation-sensitive syntax (won't support)
- [ ] SRFI 51: Handling rest list
- [ ] SRFI 54: Formatting
- [ ] SRFI 55: Require-extension
- [ ] SRFI 57: Records
- [ ] SRFI 58: Array notation
- [ ] SRFI 59: Vicinity
- [ ] SRFI 60: Integers as bits
- [ ] SRFI 61: A more general cond clause
- [-] SRFI 62: S-expression comments (part of R7RS small)
- [ ] SRFI 63: Homogeneous and heterogeneous arrays
- [ ] SRFI 64: A Scheme API for test suites
- [ ] SRFI 66: Octet vectors
- [ ] SRFI 67: Compare procedures
- [ ] SRFI 69: Basic hash tables
- [ ] SRFI 70: Numbers
- [ ] SRFI 71: Extended LET-syntax for multiple values
- [ ] SRFI 72: Hygienic macros
- [ ] SRFI 74: Octet-addressed binary blocks
- [ ] SRFI 78: Lightweight testing
- [ ] SRFI 86: MU and NU simulating VALUES & CALL-WITH-VALUES, and their related LET-syntax
- [-] SRFI 87: => in case clauses (part of R7RS small)
- [ ] SRFI 88: Keyword objects
- [ ] SRFI 89: Optional positional and named parameters
- [ ] SRFI 90: Extensible hash table constructor
- [ ] SRFI 94: Type-restricted numerical functions
- [ ] SRFI 95: Sorting and merging
- [ ] SRFI 96: SLIB prerequisites
- [ ] SRFI 97: SRFI libraries
- [ ] SRFI 98: An interface to access environment variables
- [ ] SRFI 99: ERR5RS Records

## References
* [SRFIs (status: final)](https://srfi.schemers.org/?sort=number-asc&statuses=final)
* [Gauche manual: SRFIs](http://practical-scheme.net/gauche/man/gauche-refe-draft/Standard-conformance.html#Standard-conformance)
