### ISSUE TITLE
R7RS-large tracking issue

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/vim-r7rs-syntax#8]
## List of R7RS large libraries

- [x] `(scheme list)`: Lists
- [x] `(scheme vector)`: Vectors
- [x] `(scheme vector @)`: Uniform vectors
- [x] `(scheme sort)`: Sort
- [x] `(scheme set)`: Sets
- [x] `(scheme charset)`: Character sets
- [x] `(scheme hash-table)`: Hash tables
- [x] `(scheme ilist)`: Immutable lists (#2)
- [x] `(scheme rlist)`: Random-access lists (#3)
- [x] `(scheme ideque)`: Immutable deques
- [x] `(scheme text)`: Immutable texts (#4)
- [x] `(scheme generator)`: Generators
- [x] `(scheme lseq)`: Lazy sequences
- [x] `(scheme stream)`: Stream
- [x] `(scheme box)`: Boxes
- [x] `(scheme list-queue)`: List queues
- [x] `(scheme ephemeron)`: Ephemerons
- [x] `(scheme comparator)`: Comparators
- [x] `(scheme regex)`: Regular expressions
- [x] `(scheme mapping)`: Mappings
- [x] `(scheme division)`: Integer division
- [x] `(scheme bitwise)`: Bitwise operations
- [x] `(scheme fixnum)`: Fixnum
- [x] `(scheme flonum)`: Flonum
- [x] `(scheme bytevector)`: Bytevectors (#5)
- [x] `(scheme show)`: Combinator formatting (#6)

## References
* [R7RS large (Red)](https://github.com/vmanis/r7rs-large)
* [R7RS large (Tangerine)](https://github.com/johnwcowan/r7rs-work/blob/master/TangerineEdition.md)
* [Gauche manual: R7RS large](https://practical-scheme.net/gauche/man/gauche-refe-draft/R7RS-large.html#R7RS-large)

**Comment by mnacamura** [comment]
All set, up to Tangerine edition.  Did it!
